export interface PacietnesInterface{
    nombre?: string,
    apellidos?: string,
    ci?: string,
    seguro?: string,
    telefono?: string,
    direccion?: string,
    reserva?: string,
    vigencia?: string,
    tipo?: string,
    nombrec?: string,
    cic?: string,
    telefonoc?: string,
    email?: string,
    parentesco?: string,
    antecedentes?: string,
}