CREATE DATABASE ng-games-DATABASE
USE ng_games_db

CREATE TABLE game(
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY
    titile VARCHAR (180);
    description VARCHAR (180);
    image VARCHAR (200);
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

RENAME TABLE game to games;

DESCRIBE game;